# Generated by Django 6.0 on 2026-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SMART_HINT', 'Умная подсказка'), ('FIN_TIP', 'Финансовый совет'), ('REMEMBER', 'Помните'), ('QUOTE', 'Цитата дня'), ('WISH', 'Пожелание дня')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='', max_length=160, verbose_name='Подзаголовок')),
                ('short_text', models.TextField(blank=True, default='', verbose_name='Короткий текст')),
                ('content', models.TextField(blank=True, default='', verbose_name='Полный текст (для Подробнее)')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка (ключ/название)')),
                ('color', models.CharField(blank=True, default='', max_length=30, verbose_name='Цвет (ключ)')),
                ('action_label', models.CharField(blank=True, default='', max_length=40, verbose_name='Текст кнопки (Подробнее)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Приоритет (меньше = выше)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Мотивация',
                'verbose_name_plural': 'Мотивация',
                'ordering': ('priority', '-created_at'),
            },
        ),
    ]
